### ISSUE TITLE
Radmind Assistant can't find radmind tools installer

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#100]
Using Radmind Assistant 1.0.0rc2 I tried to update my radmind tools 
using File-&gt;Install Radmind Tools.  It popped up an error message that it 
could not find the package to install BUT it did open the package anyway 
and allowed me to install.  There seems to be some confusion about the 
exact name of the tools package.  In the Resources directory the tools 
installer package has the full version name which is different than 
previous where the package was just RadmindTools.pkg.

Original comment by: shannahs

**Comment by linuxjackto1** [comment]
thanks www.movied.org
