### ISSUE TITLE
regdiff.exe Application Error

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#111]
I get a consistent error doesnt matter what is in the 
negative reg transcript.

this is performing the following command
regdiff -C -c sha1 -o 
regbasehklm.T "HKEY_LOCAL_MACHINE"

The Instruction at "0x00404b4d" referenced memory 
at "0x0037ffff".  The memory could not be "read".

this is performing the following command
regdiff -C -c sha1 -o regbasehku.T "HKEY_USERS"

The Instruction at "0x00404b94" referenced memory 
at "0x00390000".  The memory could not be "read".

attached is the negative transcript reg file.

Original comment by: tozaki

**Comment by linuxjackto1** [comment]
thanks www.movied.org
