### ISSUE TITLE
Transcript Editor Crash

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#113]
I am using Transcript Editor v0.7.6 and it will consistently crash when 
trying to add a certain file to a new transcript.  The file is a zero byte 
UNIX executable with the sticky flag on, 755 permissions and 
root:wheel ownership.  It is part of the Virex 7.7 ePO Agent for OS X.  
This is on OS X 10.4.5 with all updates applied (the machine is 
managed by Radmind).  Below is the crashlog.  Thanks in advance!!

*******************

Host Name:      ecntestmac
Date/Time:      2006-03-15 13:25:35.939 -0500
OS Version:     10.4.5 (Build 8H14)
Report Version: 4

Command: Radmind Transcript Editor
Path:    /Applications/Utilities/Radmind Assistant.app/Contents/
Resources/Radmind Transcript Editor.app/Contents/MacOS/Radmind 
Transcript Editor
Parent:  WindowServer [61]

Version: Radmind Transcript Editor version 0.7.6 (0.7.6)

PID:    3622
Thread: 7

Exception:  EXC_BREAKPOINT (0x0006)
Code[0]:    0x00000001
Code[1]:    0x92902340

Thread 0:
0   libSystem.B.dylib               0x9000b1e8 mach_msg_trap + 8
1   libSystem.B.dylib               0x9000b13c mach_msg + 60
2   com.apple.CoreFoundation        0x9075d114 __CFRunLoopRun + 
832
3   com.apple.CoreFoundation        0x9075ca18 
CFRunLoopRunSpecific + 268
4   com.apple.HIToolbox             0x9318f1e0 
RunCurrentEventLoopInMode + 264
5   com.apple.HIToolbox             0x9318e874 
ReceiveNextEventCommon + 380
6   com.apple.HIToolbox             0x9318e6e0 
BlockUntilNextEventMatchingListInMode + 96
7   com.apple.AppKit                0x9366c104 _DPSNextEvent + 384
8   com.apple.AppKit                0x9366bdc8 -[NSApplication 
nextEventMatchingMask:untilDate:inMode:dequeue:] + 116
9   com.apple.AppKit                0x93816e30 -[NSApplication 
_realDoModalLoop:peek:] + 260
10  com.apple.AppKit                0x9380d808 -[NSApplication 
runModalForWindow:] + 176
11  com.apple.AppKit                0x93808024 -[NSSavePanel
(NSSavePanelRuntime) runModalForDirectory:file:types:] + 172
12  ...ich.radmindtranscripteditor  0x000036f8 -[RXTranscript 
chooseItem:] + 216 (RXTranscript.m:306)
13  com.apple.AppKit                0x9370d270 -[NSApplication 
sendAction:to:from:] + 108
14  com.apple.AppKit                0x9370d1a4 -[NSControl 
sendAction:to:] + 96
15  com.apple.AppKit                0x9370d084 -[NSCell 
_sendActionFrom:] + 156
16  com.apple.AppKit                0x9372709c -[NSCell 
trackMouse:inRect:ofView:untilMouseUp:] + 1020
17  com.apple.AppKit                0x93726c84 -[NSButtonCell 
trackMouse:inRect:ofView:untilMouseUp:] + 564
18  com.apple.AppKit                0x937266a8 -[NSControl mouseDown:] 
+ 536
19  com.apple.AppKit                0x936c7eb0 -[NSWindow sendEvent:] + 
4616
20  com.apple.AppKit                0x93670ef4 -[NSApplication 
sendEvent:] + 4172
21  com.apple.AppKit                0x93668330 -[NSApplication run] + 
508
22  com.apple.AppKit                0x93758e68 NSApplicationMain + 452
23  ...ich.radmindtranscripteditor  0x00002878 _start + 348 (crt.c:
272)
24  ...ich.radmindtranscripteditor  0x00002718 start + 60

Thread 1:
0   libSystem.B.dylib               0x9000b1e8 mach_msg_trap + 8
1   libSystem.B.dylib               0x9000b13c mach_msg + 60
2   com.apple.CoreFoundation        0x9075d114 __CFRunLoopRun + 
832
3   com.apple.CoreFoundation        0x9075ca18 
CFRunLoopRunSpecific + 268
4   com.apple.Foundation            0x928f6384 -[NSRunLoop 
runMode:beforeDate:] + 172
5   com.apple.Foundation            0x928f62bc -[NSRunLoop run] + 
76
6   ...ich.radmindtranscripteditor  0x0000be8c +[RXAuthRW 
connectWithPorts:] + 312 (RXAuthRW.m:74)
7   com.apple.Foundation            0x928e73b4 
forkThreadForFunction + 108
8   libSystem.B.dylib               0x9002b1e0 _pthread_body + 96

Thread 2:
0   libSystem.B.dylib               0x9000b1e8 mach_msg_trap + 8
1   libSystem.B.dylib               0x9000b13c mach_msg + 60
2   com.apple.CoreFoundation        0x9075d114 __CFRunLoopRun + 
832
3   com.apple.CoreFoundation        0x9075ca18 
CFRunLoopRunSpecific + 268
4   com.apple.Foundation            0x928f6384 -[NSRunLoop 
runMode:beforeDate:] + 172
5   com.apple.Foundation            0x928f62bc -[NSRunLoop run] + 
76
6   ...ich.radmindtranscripteditor  0x0000be8c +[RXAuthRW 
connectWithPorts:] + 312 (RXAuthRW.m:74)
7   com.apple.Foundation            0x928e73b4 
forkThreadForFunction + 108
8   libSystem.B.dylib               0x9002b1e0 _pthread_body + 96

Thread 3:
0   libSystem.B.dylib               0x90049728 syscall_thread_switch + 8
1   com.apple.Foundation            0x928ff7f0 +[NSThread 
sleepUntilDate:] + 152
2   com.apple.AppKit                0x93709034 -[NSUIHeartBeat 
_heartBeatThread:] + 1100
3   com.apple.Foundation            0x928e73b4 
forkThreadForFunction + 108
4   libSystem.B.dylib               0x9002b1e0 _pthread_body + 96

Thread 4:
0   libSystem.B.dylib               0x9002e42c kevent + 12
1   com.apple.DesktopServices       0x927f65d4 
TFSNotificationTask::FSNotificationTaskProc(void*) + 56
2   ...ple.CoreServices.CarbonCore  0x90b42260 PrivateMPEntryPoint 
+ 76
3   libSystem.B.dylib               0x9002b1e0 _pthread_body + 96

Thread 5:
0   libSystem.B.dylib               0x9002b888 
semaphore_wait_signal_trap + 8
1   libSystem.B.dylib               0x9002fffc pthread_cond_wait + 488
2   ...ple.CoreServices.CarbonCore  0x90b42450 MPWaitOnQueue + 
224
3   com.apple.DesktopServices       0x927f6e20 
TNodeSyncTask::SyncTaskProc(void*) + 112
4   ...ple.CoreServices.CarbonCore  0x90b42260 PrivateMPEntryPoint 
+ 76
5   libSystem.B.dylib               0x9002b1e0 _pthread_body + 96

Thread 6:
0   libSystem.B.dylib               0x90053f48 
semaphore_timedwait_signal_trap + 8
1   libSystem.B.dylib               0x900702a8 
pthread_cond_timedwait_relative_np + 556
2   ...ple.CoreServices.CarbonCore  0x90b42450 MPWaitOnQueue + 
224
3   com.apple.DesktopServices       0x92822db4 
TIconRefTask::IconRefTaskProc(void*) + 72
4   ...ple.CoreServices.CarbonCore  0x90b42260 PrivateMPEntryPoint 
+ 76
5   libSystem.B.dylib               0x9002b1e0 _pthread_body + 96

Thread 7 Crashed:
0   com.apple.Foundation            0x92902340 _NSRaiseError + 264
1   com.apple.Foundation            0x9290207c +[NSException 
raise:format:] + 40
2   com.apple.Foundation            0x92946558 -[NSDictionary 
initWithObjects:forKeys:] + 172
3   com.apple.AppKit                0x93826000 -[NSNavFBENode 
_calculatePreviewThumbnailImage:allowComputingFromFullImage:] + 
240
4   com.apple.AppKit                0x938262f4 -[NSNavFBENode 
previewThumbnailImage] + 44
5   com.apple.AppKit                0x938d4e78 +
[NSNavFBENodePreviewHelper 
_subthreadComputePreviewThumbnailImages] + 212
6   com.apple.Foundation            0x928e73b4 
forkThreadForFunction + 108
7   libSystem.B.dylib               0x9002b1e0 _pthread_body + 96

Thread 7 crashed with PPC Thread State 64:
srr0: 0x0000000092902340 srr1: 0x000000000202f030  
vrsave: 0x0000000000000000
cr: 0x24000422          xer: 0x0000000000000007   lr: 
0x0000000092902318  ctr: 0x00000000928c413c
r0: 0x0000000000000000   r1: 0x00000000f0305b30   r2: 
0x00000000a28c1508   r3: 0x00000000f03056e0
r4: 0x0000000000000000   r5: 0x00000000928c3a64   r6: 
0x00000000f0305764   r7: 0x00000000000000ff
r8: 0x00000000f0305750   r9: 0x0000000004e50140  r10: 
0x00000000909bd648  r11: 0x0000000024000422
r12: 0x00000000928c413c  r13: 0x0000000000000000  r14: 
0x0000000000000001  r15: 0x00000000a3695f10
r16: 0x00000000f0305d70  r17: 0x0000000004e50270  r18: 
0x0000000000000000  r19: 0x0000000000000000
r20: 0x0000000000000000  r21: 0x0000000004e502c0  r22: 
0x0000000004e502b0  r23: 0x0000000000000000
r24: 0x0000000000311260  r25: 0x00000000a36a882c  r26: 
0x0000000000311260  r27: 0x0000000000000000
r28: 0x0000000004e503b0  r29: 0x00000000a28c6808  r30: 
0x00000000f0305bf0  r31: 0x0000000092902248

Binary Images Description:
0x1000 -    0x14fff edu.umich.radmindtranscripteditor Radmind 
Transcript Editor version 0.7.6 (0.7.6)   /Applications/Utilities/
Radmind Assistant.app/Contents/Resources/Radmind Transcript 
Editor.app/Contents/MacOS/Radmind Transcript Editor
0x8fe00000 - 0x8fe54fff dyld 44.2   /usr/lib/dyld
0x90000000 - 0x901b3fff libSystem.B.dylib   /usr/lib/
libSystem.B.dylib
0x9020b000 - 0x9020ffff libmathCommon.A.dylib   /usr/lib/system/
libmathCommon.A.dylib
0x90211000 - 0x90264fff com.apple.CoreText 1.0.1 (???)    /
System/Library/Frameworks/ApplicationServices.framework/Versions/
A/Frameworks/CoreText.framework/Versions/A/CoreText
0x90291000 - 0x90342fff ATS     /System/Library/Frameworks/
ApplicationServices.framework/Versions/A/Frameworks/
ATS.framework/Versions/A/ATS
0x90371000 - 0x906aefff com.apple.CoreGraphics 1.256.33 (???)
/System/Library/Frameworks/ApplicationServices.framework/
Versions/A/Frameworks/CoreGraphics.framework/Versions/A/
CoreGraphics
0x9073a000 - 0x90813fff com.apple.CoreFoundation 6.4.4 (368.25)
/System/Library/Frameworks/CoreFoundation.framework/
Versions/A/CoreFoundation
0x9085c000 - 0x9085cfff com.apple.CoreServices 10.4 (???) /
System/Library/Frameworks/CoreServices.framework/Versions/A/
CoreServices
0x9085e000 - 0x90960fff libicucore.A.dylib  /usr/lib/
libicucore.A.dylib
0x909ba000 - 0x90a3efff libobjc.A.dylib     /usr/lib/libobjc.A.dylib
0x90a68000 - 0x90ad6fff com.apple.framework.IOKit 1.4 (???)   /
System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x90aed000 - 0x90afffff libauto.dylib   /usr/lib/libauto.dylib
0x90b06000 - 0x90ddefff com.apple.CoreServices.CarbonCore 681.3 
(671.2)   /System/Library/Frameworks/CoreServices.framework/
Versions/A/Frameworks/CarbonCore.framework/Versions/A/
CarbonCore
0x90e44000 - 0x90ec4fff com.apple.CoreServices.OSServices 4.1
/System/Library/Frameworks/CoreServices.framework/Versions/
A/Frameworks/OSServices.framework/Versions/A/OSServices
0x90f0e000 - 0x90f4ffff com.apple.CFNetwork 10.4.4 (129.9)    /
System/Library/Frameworks/CoreServices.framework/Versions/A/
Frameworks/CFNetwork.framework/Versions/A/CFNetwork
0x90f64000 - 0x90f7cfff com.apple.WebServices 1.1.2 (1.1.0)   /
System/Library/Frameworks/CoreServices.framework/Versions/A/
Frameworks/WebServicesCore.framework/Versions/A/WebServicesCore
0x90f8c000 - 0x9100dfff com.apple.SearchKit 1.0.5   /System/
Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/
SearchKit.framework/Versions/A/SearchKit
0x91053000 - 0x9107dfff com.apple.Metadata 10.4.4 (121.34)
/System/Library/Frameworks/CoreServices.framework/Versions/
A/Frameworks/Metadata.framework/Versions/A/Metadata
0x9108e000 - 0x9109cfff libz.1.dylib    /usr/lib/libz.1.dylib
0x9109f000 - 0x91262fff com.apple.security 4.3 (25966)    /
System/Library/Frameworks/Security.framework/Versions/A/Security
0x91365000 - 0x9136efff com.apple.DiskArbitration 2.1   /System/
Library/Frameworks/DiskArbitration.framework/Versions/A/
DiskArbitration
0x91375000 - 0x9139cfff com.apple.SystemConfiguration 1.8.2
/System/Library/Frameworks/SystemConfiguration.framework/
Versions/A/SystemConfiguration
0x913af000 - 0x913b7fff libgcc_s.1.dylib   /usr/lib/libgcc_s.1.dylib
0x913bc000 - 0x913dcfff libmx.A.dylib   /usr/lib/libmx.A.dylib
0x913e2000 - 0x913eafff libbsm.dylib    /usr/lib/libbsm.dylib
0x913ee000 - 0x9146efff com.apple.audio.CoreAudio 3.0.2 /
System/Library/Frameworks/CoreAudio.framework/Versions/A/
CoreAudio
0x914ad000 - 0x914adfff com.apple.ApplicationServices 10.4 (???)
/System/Library/Frameworks/ApplicationServices.framework/
Versions/A/ApplicationServices
0x914af000 - 0x914e7fff com.apple.AE 1.5 (297)    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
AE.framework/Versions/A/AE
0x91502000 - 0x915cffff com.apple.ColorSync 4.4.4   /System/
Library/Frameworks/ApplicationServices.framework/Versions/A/
Frameworks/ColorSync.framework/Versions/A/ColorSync
0x91624000 - 0x916b7fff com.apple.print.framework.PrintCore 4.3 
(172.3)   /System/Library/Frameworks/
ApplicationServices.framework/Versions/A/Frameworks/
PrintCore.framework/Versions/A/PrintCore
0x916fe000 - 0x917bbfff com.apple.QD 3.8.18 (???) /System/
Library/Frameworks/ApplicationServices.framework/Versions/A/
Frameworks/QD.framework/Versions/A/QD
0x917f9000 - 0x91857fff com.apple.HIServices 1.5.1 (???)  /
System/Library/Frameworks/ApplicationServices.framework/Versions/
A/Frameworks/HIServices.framework/Versions/A/HIServices
0x91885000 - 0x918a9fff com.apple.LangAnalysis 1.6.1    /System/
Library/Frameworks/ApplicationServices.framework/Versions/A/
Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
0x918bd000 - 0x918e2fff com.apple.FindByContent 1.5 /System/
Library/Frameworks/ApplicationServices.framework/Versions/A/
Frameworks/FindByContent.framework/Versions/A/FindByContent
0x918f5000 - 0x91937fff com.apple.LaunchServices 168.10 /
System/Library/Frameworks/ApplicationServices.framework/Versions/
A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
0x91953000 - 0x91967fff com.apple.speech.synthesis.framework 3.3
/System/Library/Frameworks/ApplicationServices.framework/
Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/
SpeechSynthesis
0x91975000 - 0x919affff com.apple.ImageIO.framework 1.4.4
/System/Library/Frameworks/ApplicationServices.framework/
Versions/A/Frameworks/ImageIO.framework/Versions/A/ImageIO
0x919c4000 - 0x91a8cfff libcrypto.0.9.7.dylib   /usr/lib/libcrypto.
0.9.7.dylib
0x91ada000 - 0x91aeffff libcups.2.dylib     /usr/lib/libcups.2.dylib
0x91af4000 - 0x91b11fff libJPEG.dylib   /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libJPEG.dylib
0x91b16000 - 0x91b85fff libJP2.dylib    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libJP2.dylib
0x91b9c000 - 0x91ba0fff libGIF.dylib    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libGIF.dylib
0x91ba2000 - 0x91bd3fff libRaw.dylib    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libRaw.dylib
0x91bd7000 - 0x91c1afff libTIFF.dylib   /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libTIFF.dylib
0x91c21000 - 0x91c3afff libPng.dylib    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libPng.dylib
0x91c3f000 - 0x91c42fff libRadiance.dylib   /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libRadiance.dylib
0x91c44000 - 0x91c44fff com.apple.Accelerate 1.1.1 (Accelerate 
1.1.1) /System/Library/Frameworks/Accelerate.framework/
Versions/A/Accelerate
0x91c46000 - 0x91d30fff com.apple.vImage 2.0    /System/Library/
Frameworks/Accelerate.framework/Versions/A/Frameworks/
vImage.framework/Versions/A/vImage
0x91d38000 - 0x91d57fff com.apple.Accelerate.vecLib 3.1.1 (vecLib 
3.1.1) /System/Library/Frameworks/Accelerate.framework/
Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
0x91dc3000 - 0x91e28fff libvMisc.dylib  /System/Library/
Frameworks/Accelerate.framework/Versions/A/Frameworks/
vecLib.framework/Versions/A/libvMisc.dylib
0x91e32000 - 0x91ec4fff libvDSP.dylib   /System/Library/
Frameworks/Accelerate.framework/Versions/A/Frameworks/
vecLib.framework/Versions/A/libvDSP.dylib
0x91ede000 - 0x9246efff libBLAS.dylib   /System/Library/
Frameworks/Accelerate.framework/Versions/A/Frameworks/
vecLib.framework/Versions/A/libBLAS.dylib
0x924b6000 - 0x927c6fff libLAPACK.dylib     /System/Library/
Frameworks/Accelerate.framework/Versions/A/Frameworks/
vecLib.framework/Versions/A/libLAPACK.dylib
0x927f3000 - 0x9287ffff com.apple.DesktopServices 1.3.1 /
System/Library/PrivateFrameworks/DesktopServicesPriv.framework/
Versions/A/DesktopServicesPriv
0x928c1000 - 0x92aecfff com.apple.Foundation 6.4.4 (567.25)
/System/Library/Frameworks/Foundation.framework/Versions/C/
Foundation
0x92c0a000 - 0x92ce8fff libxml2.2.dylib     /usr/lib/libxml2.2.dylib
0x92d08000 - 0x92df6fff libiconv.2.dylib    /usr/lib/libiconv.2.dylib
0x92e08000 - 0x92e26fff libGL.dylib     /System/Library/
Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
0x92e31000 - 0x92e8bfff libGLU.dylib    /System/Library/
Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
0x92ea9000 - 0x92ea9fff com.apple.Carbon 10.4 (???)   /System/
Library/Frameworks/Carbon.framework/Versions/A/Carbon
0x92eab000 - 0x92ebffff com.apple.ImageCapture 3.0  /System/
Library/Frameworks/Carbon.framework/Versions/A/Frameworks/
ImageCapture.framework/Versions/A/ImageCapture
0x92ed7000 - 0x92ee7fff com.apple.speech.recognition.framework 
3.4 /System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/SpeechRecognition.framework/Versions/A/
SpeechRecognition
0x92ef3000 - 0x92f08fff com.apple.securityhi 2.0 (203)    /System/
Library/Frameworks/Carbon.framework/Versions/A/Frameworks/
SecurityHI.framework/Versions/A/SecurityHI
0x92f1a000 - 0x92fa1fff com.apple.ink.framework 101.2 (69)    /
System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/Ink.framework/Versions/A/Ink
0x92fb5000 - 0x92fc0fff com.apple.help 1.0.3 (32) /System/Library/
Frameworks/Carbon.framework/Versions/A/Frameworks/
Help.framework/Versions/A/Help
0x92fca000 - 0x92ff7fff com.apple.openscripting 1.2.4 (???)   /
System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/OpenScripting.framework/Versions/A/OpenScripting
0x93011000 - 0x93021fff com.apple.print.framework.Print 5.0 
(190.1)   /System/Library/Frameworks/Carbon.framework/Versions/
A/Frameworks/Print.framework/Versions/A/Print
0x9302d000 - 0x93093fff com.apple.htmlrendering 1.1.2   /
System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/HTMLRendering.framework/Versions/A/HTMLRendering
0x930c4000 - 0x93116fff com.apple.NavigationServices 3.4.2  /
System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/NavigationServices.framework/Versions/A/
NavigationServices
0x93142000 - 0x9315ffff com.apple.audio.SoundManager 3.9    /
System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/CarbonSound.framework/Versions/A/CarbonSound
0x93171000 - 0x9317efff com.apple.CommonPanels 1.2.2 (73)
/System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/CommonPanels.framework/Versions/A/CommonPanels
0x93187000 - 0x93499fff com.apple.HIToolbox 1.4.5 (???)   /
System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/HIToolbox.framework/Versions/A/HIToolbox
0x935e5000 - 0x935f1fff com.apple.opengl 1.4.7  /System/Library/
Frameworks/OpenGL.framework/Versions/A/OpenGL
0x93662000 - 0x93662fff com.apple.Cocoa 6.4 (???) /System/
Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
0x93664000 - 0x93c97fff com.apple.AppKit 6.4.4 (824.33)   /
System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
0x94024000 - 0x94094fff com.apple.CoreData 80   /System/Library/
Frameworks/CoreData.framework/Versions/A/CoreData
0x940cd000 - 0x94197fff com.apple.audio.toolbox.AudioToolbox 
1.4.1   /System/Library/Frameworks/AudioToolbox.framework/
Versions/A/AudioToolbox
0x941eb000 - 0x941ebfff com.apple.audio.units.AudioUnit 1.4
/System/Library/Frameworks/AudioUnit.framework/Versions/A/
AudioUnit
0x941ed000 - 0x94365fff com.apple.QuartzCore 1.4.5  /System/
Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
0x943af000 - 0x943ecfff libsqlite3.0.dylib  /usr/lib/
libsqlite3.0.dylib
0x943f4000 - 0x94444fff libGLImage.dylib    /System/Library/
Frameworks/OpenGL.framework/Versions/A/Libraries/
libGLImage.dylib
0x945e7000 - 0x945f6fff libCGATS.A.dylib    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
CoreGraphics.framework/Versions/A/Resources/libCGATS.A.dylib
0x945fe000 - 0x9460afff libCSync.A.dylib    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
CoreGraphics.framework/Versions/A/Resources/libCSync.A.dylib
0x94650000 - 0x94668fff libRIP.A.dylib  /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
CoreGraphics.framework/Versions/A/Resources/libRIP.A.dylib

Original comment by: mwillmore

**Comment by linuxjackto1** [comment]
thanks www.movied.org
