### ISSUE TITLE
ktcheck does not close (1.6.0fc3)

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#117]
I just installed version 1.6.0fc3 on my server and one client.  Following 
the email about displaying the compression stats I was looking to see 
the compression ratio for a setting of 5 (picked the middle).

I ran 
% sudo ktcheck -vZ 5 -c sha1 -h sthmac

And I got
&lt;&lt;&lt; f /private/etc/ssh_host_rsa_key.pub 0644 0 0 1097078494 210 
BHWUgg3QooIeULtUapTBLu/+53E=
&lt;&lt;&lt; 201 QUIT OK, closing connection
zlib stats +++ In: 20614:12533 (1.645:1) +++ Out: 6630:3379 
(1.962:1)
No updates needed

But since no updates were needed this wasn't much of a test.  And so 
the compression was only 1.5 or 2.  So I removed all my transcripts:
% sudo rm /var/radmind/client/*.T

and ran ktcheck again, which seemed to run with compression
% sudo ktcheck -vZ 5 -c sha1 -h sthmac
trying 146.201.232.114... success!
&lt;&lt;&lt; 200-RAP 1 hannahsmac.magnet.fsu.edu 1.6.0rc3 radmind access 
protocol
&lt;&lt;&lt; 200 CAPA ZLIB
&gt;&gt;&gt; COMP ZLIB 5
&lt;&lt;&lt; 320 Ready to start ZLIB compression level 5
&lt;&lt;&lt; 220 ZLIB compression level 5 enabled
&gt;&gt;&gt; STAT COMMAND
.... lots of updates....
&lt;&lt;&lt; 230 Returning STAT information
&lt;&lt;&lt; f /private/etc/ssh_host_rsa_key.pub 0644 0 0 1097078494 210 
BHWUgg3QooIeULtUapTBLu/+53E=
/var/radmind/client/special.T: created
% 

But after the special was created, there was no "QUIT" command sent 
to the server and no zlib stats printed.  I assume this is something to 
do with actually creating the special.T file?  Just a wild guess as that 
would have been the real difference.  If I just remove a single transcript 
it works fine and closes and prints the stats.  If I just remove the 
special.T transcript then it does not close and print the stats.

Original comment by: shannahs

**Comment by linuxjackto1** [comment]
thanks www.movied.org
