### ISSUE TITLE
CVS version does not build

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#122]
I tried to build the distribution from CVS.  On three different systems.

1. Under OS X.3.9 it has a loop in the Makefile.  Thus the command 
keeps getting longer...
cd libsnet; make - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 -j CC=gcc
/bin/sh: line 1: cd: libsnet: No such file or directory
cd libsnet; make - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobserver-fds=3,4 - --jobserver-fds=3,4 - --jobserver-fds=3,4 - --
jobser
etc. for many pages.

On OS X.4.4 I get a bunch of errors.  I THINK it is mainly due to libsnet 
not existing which may be the problem above.  It gives a very different 
error file though.
cd libsnet; make  CC=gcc
/bin/sh: line 1: cd: libsnet: No such file or directory

And it is looking for the file "libsnet/libsnet.la"

Original comment by: shannahs

**Comment by linuxjackto1** [comment]
thanks www.movied.org
