### ISSUE TITLE
lcksum won't verify ntfsdiff loadsets on OS X Server

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#128]
Server: OS X Server 10.3.9 running radmind 1.5.0
Client: Windows XP Pro SP2 running the current CVS release of radmind-
pc

From client: 
ntfsdiff -C -c sha1 -o xpbase.fs.T c:
then
lcreate -c sha1 -h pantherserver.myschool.edu xpbase.fs.T

then in the transcript directory on the OS X Server:
lcksum -c sha1 -n ./xpbase.fs.T

gives me hundreds of lines of:
line 2: 11 arguments should be 8
line 3: 11 arguments should be 8
line 4: 11 arguments should be 8
line 8: 11 arguments should be 8
line 16: 11 arguments should be 8
line 20: 11 arguments should be 8
line 21: 11 arguments should be 8

``` etc.
line 10733: 11 arguments should be 8
line 10734: 11 arguments should be 8
line 10735: 11 arguments should be 8
xpbase.fs.T: incorrect

Every file line in the transcript, as far as I can tell. :\(

lcksum'ing hku.T and hklm.T works just fine.

Thanks\!

Original comment by: machead
```

**Comment by linuxjackto1** [comment]
thanks www.movied.org
