### ISSUE TITLE
lapply 1.5.1/i386: retrieve AppleFile fails 

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#131]
Build the 1.5.1 release of radmind using gcc 4.0.1 on Apple Intel-based 
Mac (specifically i686-apple-darwin8-gcc-4.0.1).

Create an applicable transcript containing at least one AppleFile to be 
downloaded.

Run lapply with the transcript you created above.

lapply fails with "retreive applefile xxxx failed: corrupt AppleSingle-
encoded file".

Replace the radmind tools with PPC binaries, run lapply with the same 
transcript, and it succeeds.

Original comment by: gneagle

**Comment by linuxjackto1** [comment]
thanks www.movied.org
