### ISSUE TITLE
fsdiff looks in directories found in negative transripts

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#134]
Applies to version 1.5.1 on FreeBSD 6.0

When working with a command file like so:

p base.T
n negative.T

with, for e.g.:

base.T:

f /foo/bar 0644 0 0 ...

negative.T:

d /foo 0555 0 0

'fsdiff -A' will still claim updates are needed inside
/foo if the filesystem contents differ from those
listed in base.T ('+' entries are added to the diff
output).

This behavior seems non-intuitive and incorrect.  If
the directory is listed in the higher precedence
negative transcript, fsdiff should not descend into it
at all, no matter the contents of the lower precedence
transcript.  That's the impression I get from the
fsdiff man page too.

Original comment by: krwebb

**Comment by linuxjackto1** [comment]
thanks www.movied.org
