### ISSUE TITLE
Setup assistant bug - loadset isn't moved

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#140]
To reproduce setup new server. Go to client, select run setup steps. Select 
2nd option, slect neg, cointinue to the end.

Go to server, refresh, press OK to "Would you like the Server Manager to 
update it and make it available to client machines?"

loadset is verified - but it stays in new uploaded section instead of 
moving up.

Original comment by: ofirgal

**Comment by linuxjackto1** [comment]
thanks www.movied.org
