### ISSUE TITLE
lapply create symlinks the OS X can't follow

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#141]
This is a patch derived from the thread "1.6.0
lockdown?" radmind-devel.

The attached patch removes -u from lapply and lfdiff. 
Instead, retr() and retr_applefile() take an additional
value mode_t tempmode to specify how temp files are
created.

ktcheck uses 0666 while lapply and lfdiff use 0600.

Original comment by: umeditor

**Comment by linuxjackto1** [comment]
thanks www.movied.org
