### ISSUE TITLE
Transcript Editor crashes on save

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#150]
On Intel Mac, create a new transcript; drag a few files or folders into 
the transcript window, attempt to save.  RTE crashes with a divide by 
zero error:

Date/Time:      2006-03-27 15:37:41.250 -0800
OS Version:     10.4.5 (Build 8G1454)
Report Version: 4

Command: Radmind Transcript Editor
Path:    /Applications/Utilities/radmind/Radmind Transcript 
Editor.app/Contents/MacOS/Radmind Transcript Editor
Parent:  WindowServer [93]

Version: Radmind Transcript Editor version 0.7.7 (0.7.7)

PID:    1303
Thread: 0

Exception:  EXC_ARITHMETIC (0x0003)
Codes:      EXC_I386_DIV (divide by zero)

Thread 0 Crashed:
0   ...ich.radmindtranscripteditor  0x00009b0a -[RXTranscript 
writeToFile:ofType:] + 1643 (RXTranscript.m:2468)
1   com.apple.AppKit                0x9360ca4a -[NSDocument 
writeSafelyToURL:ofType:forSaveOperation:error:] + 167
2   com.apple.AppKit                0x9360c7a7 -[NSDocument 
saveToURL:ofType:forSaveOperation:error:] + 203
3   com.apple.AppKit                0x936ff445 -[NSDocument 
_saveToURL:ofType:forSaveOperation:delegate:didSaveSelector:contextI
nfo:] + 63
4   com.apple.AppKit                0x9360c6d1 -[NSDocument 
saveToURL:ofType:forSaveOperation:delegate:didSaveSelector:contextIn
fo:] + 859
5   com.apple.AppKit                0x9363e45f -[NSDocument 
_savePanelWasPresented:withResult:inContext:] + 459
6   com.apple.AppKit                0x935afe78 -[NSSavePanel
(NSSavePanelRuntime) _didEndSheet:returnCode:contextInfo:] + 306
7   com.apple.AppKit                0x934e89e2 -[NSApplication 
endSheet:returnCode:] + 359
8   com.apple.AppKit                0x9357ef92 -[NSSavePanel
(NSSavePanelRuntime) ok:] + 311
9   com.apple.AppKit                0x9345f1bc -[NSApplication 
sendAction:to:from:] + 107
10  com.apple.AppKit                0x9345f115 -[NSControl 
sendAction:to:] + 101
11  com.apple.AppKit                0x934612c5 -[NSCell 
_sendActionFrom:] + 168
12  com.apple.AppKit                0x93473a91 -[NSCell 
trackMouse:inRect:ofView:untilMouseUp:] + 1271
13  com.apple.AppKit                0x934915b8 -[NSButtonCell 
trackMouse:inRect:ofView:untilMouseUp:] + 875
14  com.apple.AppKit                0x93490e4d -[NSControl mouseDown:] 
+ 757
15  com.apple.AppKit                0x9344e7d3 -[NSWindow sendEvent:] + 
5279
16  com.apple.AppKit                0x9388e5b5 -[NSSavePanel sendEvent:] 
+ 423
17  com.apple.AppKit                0x93440858 -[NSApplication 
sendEvent:] + 5023
18  com.apple.AppKit                0x9336b466 -[NSApplication run] + 
547
19  com.apple.AppKit                0x9335f397 NSApplicationMain + 573
20  ...ich.radmindtranscripteditor  0x00001fce _start + 228 (crt.c:
272)
21  ...ich.radmindtranscripteditor  0x00001ee9 start + 41

Thread 1:
0   libSystem.B.dylib               0x9000a607 mach_msg_trap + 7
1   com.apple.CoreFoundation        0x9082295e 
CFRunLoopRunSpecific + 2014
2   com.apple.CoreFoundation        0x90822179 
CFRunLoopRunInMode + 61
3   com.apple.Foundation            0x9272eb4a -[NSRunLoop 
runMode:beforeDate:] + 182
4   com.apple.Foundation            0x9272ea46 -[NSRunLoop run] + 
75
5   ...ich.radmindtranscripteditor  0x0000cb72 +[RXAuthRW 
connectWithPorts:] + 348 (RXAuthRW.m:75)
6   com.apple.Foundation            0x926f91b0 
forkThreadForFunction + 123
7   libSystem.B.dylib               0x90024b47 _pthread_body + 84

Thread 2:
0   libSystem.B.dylib               0x9003fb5f syscall_thread_switch + 7
1   com.apple.AppKit                0x93448a8e -[NSUIHeartBeat 
_heartBeatThread:] + 1399
2   com.apple.Foundation            0x926f91b0 
forkThreadForFunction + 123
3   libSystem.B.dylib               0x90024b47 _pthread_body + 84

Thread 3:
0   libSystem.B.dylib               0x9002767c kevent + 12
1   ...ple.CoreServices.CarbonCore  0x90ca8c34 PrivateMPEntryPoint + 
51
2   libSystem.B.dylib               0x90024b47 _pthread_body + 84

Thread 4:
0   libSystem.B.dylib               0x900251e7 
semaphore_wait_signal_trap + 7
1   ...ple.CoreServices.CarbonCore  0x90ca8dda MPWaitOnQueue + 
198
2   com.apple.DesktopServices       0x9261efff 
TNodeSyncTask::SyncTaskProc(void*) + 143
3   ...ple.CoreServices.CarbonCore  0x90ca8c34 PrivateMPEntryPoint + 
51
4   libSystem.B.dylib               0x90024b47 _pthread_body + 84

Thread 5:
0   libSystem.B.dylib               0x90049337 
semaphore_timedwait_signal_trap + 7
1   ...ple.CoreServices.CarbonCore  0x90ca8dda MPWaitOnQueue + 
198
2   com.apple.DesktopServices       0x92642b71 
TIconRefTask::IconRefTaskProc(void*) + 87
3   ...ple.CoreServices.CarbonCore  0x90ca8c34 PrivateMPEntryPoint + 
51
4   libSystem.B.dylib               0x90024b47 _pthread_body + 84

Thread 0 crashed with i386 Thread State:
eax: 0x00000000    ebx: 0x00000000 ecx:0x01800038 edx: 
0x00000000
edi: 0x00326a80    esi: 0x00000000 ebp:0xbffff2b8 esp: 0xbfffedf0
ss: 0x0000002f    efl: 0x00010282 eip:0x00009b0a  cs: 0x00000027
ds: 0x0000002f     es: 0x0000002f  fs:0x00000000  gs: 0x00000037

Binary Images Description:
0x1000 -    0x18fff edu.umich.radmindtranscripteditor Radmind 
Transcript Editor version 0.7.7 (0.7.7)   /Applications/Utilities/
radmind/Radmind Transcript Editor.app/Contents/MacOS/Radmind 
Transcript Editor
0x14c3b000 - 0x14c3dfff com.apple.AutomatorCMM 1.0.1 (68)
/System/Library/Contextual Menu Items/AutomatorCMM.plugin/
Contents/MacOS/AutomatorCMM
0x14c41000 - 0x14c45fff com.apple.FolderActionsMenu 1.3.1
/System/Library/Contextual Menu Items/
FolderActionsMenu.plugin/Contents/MacOS/FolderActionsMenu
0x14c4a000 - 0x14c4afff com.apple.SpotLightCM 1.0 (121.34)
/System/Library/Contextual Menu Items/SpotlightCM.plugin/
Contents/MacOS/SpotlightCM
0x14c4e000 - 0x14c4ffff com.symantec.NAVCMPlugIn 10.1 (003)
/Library/Contextual Menu Items/NAVCMPlugIn.plugin/Contents/
MacOS/NAVCMPlugIn
0x8fe00000 - 0x8fe4bfff dyld 44.17  /usr/lib/dyld
0x90000000 - 0x9016efff libSystem.B.dylib   /usr/lib/
libSystem.B.dylib
0x901be000 - 0x901c0fff libmathCommon.A.dylib   /usr/lib/system/
libmathCommon.A.dylib
0x901c2000 - 0x901fefff com.apple.CoreText 1.1.0 (???)    /System/
Library/Frameworks/ApplicationServices.framework/Versions/A/
Frameworks/CoreText.framework/Versions/A/CoreText
0x90225000 - 0x902fafff ATS     /System/Library/Frameworks/
ApplicationServices.framework/Versions/A/Frameworks/
ATS.framework/Versions/A/ATS
0x9031a000 - 0x90769fff com.apple.CoreGraphics 1.258.23 (???)
/System/Library/Frameworks/ApplicationServices.framework/
Versions/A/Frameworks/CoreGraphics.framework/Versions/A/
CoreGraphics
0x90800000 - 0x908c8fff com.apple.CoreFoundation 6.4.5 (368.26)
/System/Library/Frameworks/CoreFoundation.framework/
Versions/A/CoreFoundation
0x90906000 - 0x90906fff com.apple.CoreServices 10.4 (???) /
System/Library/Frameworks/CoreServices.framework/Versions/A/
CoreServices
0x90908000 - 0x909fbfff libicucore.A.dylib  /usr/lib/
libicucore.A.dylib
0x90a4b000 - 0x90acafff libobjc.A.dylib     /usr/lib/libobjc.A.dylib
0x90af3000 - 0x90b56fff libstdc++.6.dylib   /usr/lib/libstdc++.
6.dylib
0x90bc5000 - 0x90bccfff libgcc_s.1.dylib   /usr/lib/libgcc_s.1.dylib
0x90bd1000 - 0x90c41fff com.apple.framework.IOKit 1.4.2 (???)
/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x90c56000 - 0x90c68fff libauto.dylib   /usr/lib/libauto.dylib
0x90c6e000 - 0x90f13fff com.apple.CoreServices.CarbonCore 682.9 
(679) /System/Library/Frameworks/CoreServices.framework/
Versions/A/Frameworks/CarbonCore.framework/Versions/A/
CarbonCore
0x90f56000 - 0x90fbefff com.apple.CoreServices.OSServices 4.1
/System/Library/Frameworks/CoreServices.framework/Versions/
A/Frameworks/OSServices.framework/Versions/A/OSServices
0x90ff6000 - 0x91033fff com.apple.CFNetwork 129.10  /System/
Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/
CFNetwork.framework/Versions/A/CFNetwork
0x91045000 - 0x91055fff com.apple.WebServices 1.1.3 (1.1.0)
/System/Library/Frameworks/CoreServices.framework/Versions/
A/Frameworks/WebServicesCore.framework/Versions/A/
WebServicesCore
0x91060000 - 0x910defff com.apple.SearchKit 1.0.5   /System/
Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/
SearchKit.framework/Versions/A/SearchKit
0x91113000 - 0x91131fff com.apple.Metadata 10.4.4 (121.35)
/System/Library/Frameworks/CoreServices.framework/Versions/
A/Frameworks/Metadata.framework/Versions/A/Metadata
0x9113d000 - 0x9114bfff libz.1.dylib    /usr/lib/libz.1.dylib
0x9114e000 - 0x91301fff com.apple.security 4.2.1 (24989)  /
System/Library/Frameworks/Security.framework/Versions/A/Security
0x913ef000 - 0x913f7fff com.apple.DiskArbitration 2.1   /System/
Library/Frameworks/DiskArbitration.framework/Versions/A/
DiskArbitration
0x913fe000 - 0x91424fff com.apple.SystemConfiguration 1.8.5
/System/Library/Frameworks/SystemConfiguration.framework/
Versions/A/SystemConfiguration
0x91436000 - 0x9143dfff libbsm.dylib    /usr/lib/libbsm.dylib
0x91441000 - 0x914bafff com.apple.audio.CoreAudio 3.0.2 /
System/Library/Frameworks/CoreAudio.framework/Versions/A/
CoreAudio
0x91508000 - 0x91508fff com.apple.ApplicationServices 10.4 (???)
/System/Library/Frameworks/ApplicationServices.framework/
Versions/A/ApplicationServices
0x9150a000 - 0x91535fff com.apple.AE 314 (313)    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
AE.framework/Versions/A/AE
0x91548000 - 0x9161cfff com.apple.ColorSync 4.4.6   /System/
Library/Frameworks/ApplicationServices.framework/Versions/A/
Frameworks/ColorSync.framework/Versions/A/ColorSync
0x91655000 - 0x916d2fff com.apple.print.framework.PrintCore 4.4 
(177.6)   /System/Library/Frameworks/
ApplicationServices.framework/Versions/A/Frameworks/
PrintCore.framework/Versions/A/PrintCore
0x916ff000 - 0x917a9fff com.apple.QD 3.10.7 (???) /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
QD.framework/Versions/A/QD
0x917cf000 - 0x9181afff com.apple.HIServices 1.5.2 (???)  /
System/Library/Frameworks/ApplicationServices.framework/Versions/
A/Frameworks/HIServices.framework/Versions/A/HIServices
0x91839000 - 0x9184ffff com.apple.LangAnalysis 1.6.3    /System/
Library/Frameworks/ApplicationServices.framework/Versions/A/
Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
0x9185b000 - 0x91875fff com.apple.FindByContent 1.5 /System/
Library/Frameworks/ApplicationServices.framework/Versions/A/
Frameworks/FindByContent.framework/Versions/A/FindByContent
0x9187f000 - 0x918bcfff com.apple.LaunchServices 176    /System/
Library/Frameworks/ApplicationServices.framework/Versions/A/
Frameworks/LaunchServices.framework/Versions/A/LaunchServices
0x918d0000 - 0x918dbfff com.apple.speech.synthesis.framework 3.4
/System/Library/Frameworks/ApplicationServices.framework/
Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/
SpeechSynthesis
0x918e2000 - 0x91916fff com.apple.ImageIO.framework 1.4.4
/System/Library/Frameworks/ApplicationServices.framework/
Versions/A/Frameworks/ImageIO.framework/Versions/A/ImageIO
0x91928000 - 0x919dafff libcrypto.0.9.7.dylib   /usr/lib/libcrypto.
0.9.7.dylib
0x91a20000 - 0x91a36fff libcups.2.dylib     /usr/lib/libcups.2.dylib
0x91a3b000 - 0x91a57fff libJPEG.dylib   /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libJPEG.dylib
0x91a5c000 - 0x91abafff libJP2.dylib    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libJP2.dylib
0x91aca000 - 0x91acefff libGIF.dylib    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libGIF.dylib
0x91ad0000 - 0x91b07fff libRaw.dylib    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libRaw.dylib
0x91b0a000 - 0x91b4dfff libTIFF.dylib   /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libTIFF.dylib
0x91b53000 - 0x91b6dfff libPng.dylib    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libPng.dylib
0x91b72000 - 0x91b74fff libRadiance.dylib   /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
ImageIO.framework/Versions/A/Resources/libRadiance.dylib
0x91b76000 - 0x91b76fff com.apple.Accelerate 1.2.1 (Accelerate 
1.2.1) /System/Library/Frameworks/Accelerate.framework/
Versions/A/Accelerate
0x91b78000 - 0x91bfbfff com.apple.vImage 2.2    /System/Library/
Frameworks/Accelerate.framework/Versions/A/Frameworks/
vImage.framework/Versions/A/vImage
0x91c02000 - 0x91c02fff com.apple.Accelerate.vecLib 3.2.1 (vecLib 
3.2.1) /System/Library/Frameworks/Accelerate.framework/
Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
0x91c04000 - 0x91c49fff libvMisc.dylib  /System/Library/
Frameworks/Accelerate.framework/Versions/A/Frameworks/
vecLib.framework/Versions/A/libvMisc.dylib
0x91c51000 - 0x91c76fff libvDSP.dylib   /System/Library/
Frameworks/Accelerate.framework/Versions/A/Frameworks/
vecLib.framework/Versions/A/libvDSP.dylib
0x91c7d000 - 0x92200fff libBLAS.dylib   /System/Library/
Frameworks/Accelerate.framework/Versions/A/Frameworks/
vecLib.framework/Versions/A/libBLAS.dylib
0x9223d000 - 0x925effff libLAPACK.dylib     /System/Library/
Frameworks/Accelerate.framework/Versions/A/Frameworks/
vecLib.framework/Versions/A/libLAPACK.dylib
0x9261c000 - 0x926a0fff com.apple.DesktopServices 1.3.2 /
System/Library/PrivateFrameworks/DesktopServicesPriv.framework/
Versions/A/DesktopServicesPriv
0x926dc000 - 0x9290efff com.apple.Foundation 6.4.5 (567.26)
/System/Library/Frameworks/Foundation.framework/Versions/C/
Foundation
0x92a1a000 - 0x92af8fff libxml2.2.dylib     /usr/lib/libxml2.2.dylib
0x92b15000 - 0x92c02fff libiconv.2.dylib    /usr/lib/libiconv.2.dylib
0x92c12000 - 0x92c29fff libGL.dylib     /System/Library/
Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
0x92c34000 - 0x92c8bfff libGLU.dylib    /System/Library/
Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
0x92c9f000 - 0x92c9ffff com.apple.Carbon 10.4 (???)   /System/
Library/Frameworks/Carbon.framework/Versions/A/Carbon
0x92ca1000 - 0x92cb1fff com.apple.ImageCapture 3.0.3    /System/
Library/Frameworks/Carbon.framework/Versions/A/Frameworks/
ImageCapture.framework/Versions/A/ImageCapture
0x92cbf000 - 0x92cc7fff com.apple.speech.recognition.framework 
3.5 /System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/SpeechRecognition.framework/Versions/A/
SpeechRecognition
0x92ccd000 - 0x92cd2fff com.apple.securityhi 2.0.1 (24742)    /
System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/SecurityHI.framework/Versions/A/SecurityHI
0x92cd8000 - 0x92d69fff com.apple.ink.framework 101.2.1 (71)
/System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/Ink.framework/Versions/A/Ink
0x92d7d000 - 0x92d80fff com.apple.help 1.0.3 (32.1)   /System/
Library/Frameworks/Carbon.framework/Versions/A/Frameworks/
Help.framework/Versions/A/Help
0x92d83000 - 0x92da0fff com.apple.openscripting 1.2.3 (???)   /
System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/OpenScripting.framework/Versions/A/OpenScripting
0x92db0000 - 0x92db6fff com.apple.print.framework.Print 5.1 
(192.3)   /System/Library/Frameworks/Carbon.framework/Versions/
A/Frameworks/Print.framework/Versions/A/Print
0x92dbc000 - 0x92e1ffff com.apple.htmlrendering 66.1 (1.1.3)
/System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/HTMLRendering.framework/Versions/A/HTMLRendering
0x92e43000 - 0x92e84fff com.apple.NavigationServices 3.4.3  /
System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/NavigationServices.framework/Versions/A/
NavigationServices
0x92eab000 - 0x92eb8fff com.apple.audio.SoundManager 3.9.1
/System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/CarbonSound.framework/Versions/A/CarbonSound
0x92ebf000 - 0x92ec4fff com.apple.CommonPanels 1.2.3 (73)
/System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/CommonPanels.framework/Versions/A/CommonPanels
0x92ec9000 - 0x931bbfff com.apple.HIToolbox 1.4.5 (???)   /
System/Library/Frameworks/Carbon.framework/Versions/A/
Frameworks/HIToolbox.framework/Versions/A/HIToolbox
0x932c0000 - 0x932cbfff com.apple.opengl 1.4.8  /System/Library/
Frameworks/OpenGL.framework/Versions/A/OpenGL
0x93358000 - 0x93358fff com.apple.Cocoa 6.4 (???) /System/
Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
0x9335a000 - 0x93a13fff com.apple.AppKit 6.4.5 (824.35)   /
System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
0x93d94000 - 0x93e0efff com.apple.CoreData 90   /System/Library/
Frameworks/CoreData.framework/Versions/A/CoreData
0x93e47000 - 0x93f07fff com.apple.audio.toolbox.AudioToolbox 
1.4.2   /System/Library/Frameworks/AudioToolbox.framework/
Versions/A/AudioToolbox
0x93f46000 - 0x93f46fff com.apple.audio.units.AudioUnit 1.4.2
/System/Library/Frameworks/AudioUnit.framework/Versions/A/
AudioUnit
0x93f48000 - 0x940fdfff com.apple.QuartzCore 1.4.4  /System/
Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
0x94143000 - 0x94184fff libsqlite3.0.dylib  /usr/lib/
libsqlite3.0.dylib
0x9418c000 - 0x941c5fff libGLImage.dylib    /System/Library/
Frameworks/OpenGL.framework/Versions/A/Libraries/
libGLImage.dylib
0x94340000 - 0x9434ffff libCGATS.A.dylib    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
CoreGraphics.framework/Versions/A/Resources/libCGATS.A.dylib
0x94356000 - 0x94361fff libCSync.A.dylib    /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
CoreGraphics.framework/Versions/A/Resources/libCSync.A.dylib
0x943ad000 - 0x943c7fff libRIP.A.dylib  /System/Library/
Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
CoreGraphics.framework/Versions/A/Resources/libRIP.A.dylib

Model: MacBookPro1,1, BootROM MBP11.0044.B02, 2 processors, Intel 
Core Duo, 2 GHz, 1 GB
Graphics: ATI Radeon X1600, ATY,RadeonX1600, PCIe, 256 MB
Memory Module: DIMM1/BANK 1, 1 GB, DDR2 SDRAM, 667 MHz
AirPort: spairport_wireless_card_type_airport_extreme (0x168C, 0x86), 
0.1.12
Bluetooth: Version 1.7.2f10, 2 service, 1 devices, 1 incoming serial 
ports
Network Service: Built-in Ethernet, Ethernet, en0
PCI Card: ethernet, sppci_ethernet, Airport
Serial ATA Device: FUJITSU MHV2100BH, 93.16 GB
Parallel ATA Device: MATSHITADVD-R   UJ-857
USB Device: Built-in iSight, Micron, Up to 480 Mb/sec, 500 mA
USB Device: Apple Internal Keyboard / Trackpad, Apple Computer, Up 
to 12 Mb/sec, 500 mA
USB Device: Bluetooth HCI, Up to 12 Mb/sec, 500 mA
USB Device: IR Receiver, Apple Computer, Inc., Up to 12 Mb/sec, 500 
mA

Original comment by: gneagle

**Comment by linuxjackto1** [comment]
thanks www.movied.org
