### ISSUE TITLE
problem with sort order on default 10.4 transcript

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#157]
when i try to upload the 10.4 desktop transcript with radmind assistant 
1.0 to mac 10.4.6 client hosting the radmind server i get an error 
message on the server.

the message says bad sort order in line 8: the /.vols line. when i comment 
out line 8 it tells me there is a problem with line 6. i comment out line 6 
and then it tells me there is a problem with line twenty something. after i 
comment out that line it tells me there was a problem with the verify and 
no additional information.

i then delete the negative and try again. sometimes i encounter a problem 
with the assistant on the radmind assistant crashing on the radmind 
client. sometimes it goes ok and i can try a re upload. if it goes ok i get 
the same error message consistently.

case sensistivity is disabled on both radmind server and client.

Original comment by: marknassy

**Comment by linuxjackto1** [comment]
thanks www.movied.org
