### ISSUE TITLE
"Loadset and Transcript Manager" subfolder problem

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#159]
The "Loadset and Transcript Manager" component of
Radmind Assistant (1.0) does not deal with folders
well.  Suppose I have the following file structure:
1.T
2.T
3 (a folder)
A.T
B.T
4.T
5.T

Where 1,2,4 and 5.T are transcripts in the top level,
and '3' is a folder containing A.T and B.T.  Leave the
folder in the non-expanded state in the GUI (so that A
and B are not visible).  Click on 5.T, then click the
"Edit" button to open the Transcript Editor.  The
transcript editor opens showing the contents of B.T
instead of 5.T.  If the folder is expanded in the GUI,
then clicking the edit button with 5.T highlighted
opens 5.T as expected.  In other words, if the folder
contents are hidden, and I choose the fourth item down
in the list (not including the folder - i.e. 5.T), the
Transcript Editor opens the fourth item down, but
includes the items in the folder in its counting.

The "Verify" and "Edit" buttons do not show this same
problem- they behave as expected.  So far I've only
seen it with the edit button, but the behavior is
consistent.

Original comment by: ktgraham

**Comment by linuxjackto1** [comment]
thanks www.movied.org
