### ISSUE TITLE
All Apps in RadmindAssistant-1.0.0rc2 didn't work!

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#17]
All apps in the RadmindAssistant-1.0.0rc2 seams to be not correctly
compiled. I think it's the "Release" Option in XCode isn't set. This 
produce the error. 

Error looks like:

"dyld: /Users/admin/Desktop/Radmind/Radmind Assistant.app/
Contents/Resources/rmauthexec can't open library: /System/Library/
PrivateFrameworks/ZeroLink.framework/Versions/A/ZeroLink  (No 
such file or directory, errno = 2)"

I think this couldn't be reproduced on the machine where the apps
are compiled on.

I tested it on 10.3.9 and 10.4.5.

Best regards
Erik Lehmann

Original comment by: reisswolf

**Comment by linuxjackto1** [comment]
thanks www.movied.org
