### ISSUE TITLE
compile error 1.6.0

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#179]
I just tried to compile 1.6.0 and it failed.  I
installed 1.5.0 before
without issue.  I just do the configure, make, then
make install.  Here is
the error

[blah radmind-1.6.0]$ make
cd libsnet; make  CC=gcc
make[1]: Entering directory
`/home/sbw913/radmind-1.6.0/libsnet'
./libtool --quiet --mode=compile \
gcc -c  -Wall -Wmissing-prototypes -I. snet.c
building profiled snet.o
./libtool --quiet --mode=link \
gcc -o libsnet.la snet.lo -rpath /lib -version-info 0:0:0
building profiled libsnet.la
make[1]: Leaving directory
`/home/sbw913/radmind-1.6.0/libsnet'
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I. \
-DVERSION=\"`cat ./VERSION`\" \
-c ./version.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I. \
-D_RADMIND_AUTHLEVEL=0 \
-D_RADMIND_PATH=\"/var/radmind\" \
-D_RADMIND_LOG=LOG_LOCAL7 \
-D_RADMIND_MAXCONNECTIONS=0 \
-c ./daemon.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I. \
-c ./command.c
./command.c: In function `f_stor':
./command.c:873: warning: long long int format, off_t
arg (arg 3)
./command.c: In function `f_login':
./command.c:1058: warning: initialization from
incompatible pointer type
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o argcargv.o
argcargv.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o code.o code.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o cksum.o
cksum.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o base64.o
base64.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o mkdirs.o
mkdirs.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o applefile.o
applefile.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o connect.o
connect.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o list.o list.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o wildcard.o
wildcard.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o logname.o
logname.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o pathcmp.o
pathcmp.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I. \
-D_RADMIND_TLS_CA=\"/var/radmind/cert/ca.pem\" \

-D_RADMIND_TLS_CERT=\"/var/radmind/cert/cert.pem\" \
-c ./tls.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-o radmind version.o
daemon.o command.o argcargv.o code.o cksum.o base64.o
mkdirs.o applefile.o
connect.o list.o wildcard.o logname.o pathcmp.o tls.o
-Llibsnet/.libs
-lsnet -lcrypto -lssl -lnsl  -lpam -lz
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I. \

-D_RADMIND_COMMANDFILE=\"/var/radmind/client/command.K\" \
-c ./fsdiff.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I. \
-D_RADMIND_PATH=\"/var/radmind\" \
-c ./transcript.c
./transcript.c: In function `t_print':
./transcript.c:346: warning: long long int format,
__off_t arg (arg 9)
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o llist.o
llist.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o hardlink.o
hardlink.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o radstat.o
radstat.c
gcc -o fsdiff version.o fsdiff.o argcargv.o
transcript.o llist.o code.o
hardlink.o cksum.o base64.o pathcmp.o radstat.o
applefile.o list.o
-Llibsnet/.libs  -lsnet -lcrypto -lssl -lnsl  -lpam -lz
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I. \
-D_RADMIND_PATH=\"/var/radmind\" \
-D_RADMIND_HOST=\"radmind\" \
-D_RADMIND_AUTHLEVEL=0 \

-D_RADMIND_COMMANDFILE=\"/var/radmind/client/command.K\" \
-c ./ktcheck.c
gcc  -Wall -Wmissing-prototypes -g -O2 -I./libsnet -I.
-c -o retr.o retr.c
retr.c: In function `retr':
retr.c:115: warning: long long int format, off_t arg
(arg 2)
retr.c: At top level:
retr.c:518: error: conflicting types for 'retr_applefile'
connect.h:18: error: previous declaration of
'retr_applefile' was here
retr.c:518: error: conflicting types for 'retr_applefile'
connect.h:18: error: previous declaration of
'retr_applefile' was here
make: *** [retr.o] Error 1

This is on Red Hat Enterprise Linux AS release 4
(Nahant Update 3) fully
updated.

Uname output: 2.6.9-34.ELsmp #1 SMP Fri Feb 24 16:56:28
EST 2006 x86_64
x86_64 x86_64 GNU/Linux

[blah radmind-1.6.0]$ gcc -v
Reading specs from
/usr/lib/gcc/x86_64-redhat-linux/3.4.5/specs
Configured with: ../configure --prefix=/usr
--mandir=/usr/share/man
--infodir=/usr/share/info --enable-shared
--enable-threads=posix
--disable-checking --with-system-zlib --enable-__cxa_atexit
--disable-libunwind-exceptions --enable-java-awt=gtk
--host=x86_64-redhat-linux
Thread model: posix
gcc version 3.4.5 20051201 (Red Hat 3.4.5-2)

Thanks
Reed

Original comment by: rgzoso2

**Comment by linuxjackto1** [comment]
thanks www.movied.org
