### ISSUE TITLE
Transcript Editor - Show Info Button & Command

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#20]
The Radmind Transcript Editor 0.7.7rc1 (0.7.7rc1) displays "Show Info" 
command in the "File" menu when you already are displaying info using 
the "Show Info"button. Also, if you use the "Show Info" command in the 
"File" menu, it changes to "Hide Info" as does the button. But, if you click 
on the button, the button changes to "Show Info", but the command in the 
menu does not.

If you select the "Show Info" command in the "File" menu it changes to 
"Hide Info" and the button also displays "Hide Info". If you then select 
"Hide Info" command from the "File" menu, it changed to "Show Info" and 
the button also changed to "Show Info"

So, it looks like using the "Show Info" or "Hide Info" button doesn't change 
command, but the command changes the button.

Original comment by: uurazzle

**Comment by linuxjackto1** [comment]
thanks www.movied.org
