### ISSUE TITLE
Server Manger 0.9.5 edits wrong transcript

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#22]
Problem:
---------

\- Clicking 'edit' opens the wrong transcript in the editor. 

Steps to repeat:
----------------

we have this structure:

var/radmind &gt; tree transcript
|--10.4.3-10.4.5_8H14.T
|--10.4.3mpc_base.T
|--adobe
|----adobeCS2.commonFiles.T
|----bridge1.0-1.0.3.update.T
|----illustratorCS2.applicationonly.T
|----photoshop.illustrator.CS2.helpfix.T
|----photoshopCS2.applicationonly.T
|--configs
|----disk1.nfsexport.T
|----RadmindDaily.T
|----tempLoginHook.T
|--drivers
|----WacomDriver.493-3.T
|--negatives
|----Combustion3.negative.T
|----Commotion4.1.negative.T
|----mpc-negative_2006-03-21-a.T
|--other
|----jobsSymLink.T
|--Quicktime.7.0.3-7.0.4.T
|--registrations
|----photoshop.CS2.volumeserial.T
|----photoshop.illustrator.CS2.volumeserial.T
|----Quicktime.7.proKey.T
|--SecurityUpdate.2006-001-10.4.5.T
|--software
|----ChickenOfTheVNC.T
|----Commotion.4.1.T
|----DVCPROHD_HDV_codecs.T
|----FinalCutPro.5.noreg.T
|----iDVD5.0.noThemes.T
|----iPhoto5.0.1.T
|----LinotypeFontExplorerX.101.T
|----Office2004.11.2.3.T
|----RealOnePlayer9.T
|----RemoteDesktopAdminAuth.T

Clicking 'edit' in the transcript manager with 'software/
ChickenOfTheVNC.T' selected, opens 'configs/disk1.nfsexport.T' in the 
editor.

cheers,
tom

Original comment by: tomcowland

**Comment by linuxjackto1** [comment]
thanks www.movied.org
