### ISSUE TITLE
Display anomoly in Radmind Server Manager

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#24]
Some items not displayed in Nested command file folders. I'm not quite 
sure what the pattern is yet to what files are displayed and hidden. In the 
example, the iPhoto file was previously displayed when there were only 
two files. With the addition of the iDVD file the iPhoto file went invisible. 
Resizing the window, restarting the app and rebooting the machine have 
made no difference. 10.4.5 to 10.4.6 also made no difference.

Screenshot attached.

Sam Agnew

Original comment by: samagnew

**Comment by linuxjackto1** [comment]
thanks www.movied.org
