### ISSUE TITLE
ra.sh prompt changes

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#243]
When I run ra.sh, I get these prompts:

Edit difference transcript (or apply)? [Yn]
Apply difference transcript? [Yn]

I've since learned a secret, that the first prompt will
accept an 'a' for apply. I think the current prompting
is clunky. I don't like how the 'Y' answers mean three
different things:

1) ktcheck
2) edit the fsdiff
3) lapply

I think these can be easily condensed, clarified, and
made more usable. For example, our old radload script
would prompt like this:

lapply whisper.web.itd.umich.edu[ y | n | e ]?

The 'e' was for edit, if you chose that, you'd get the
same prompt again after completing an edit. This offers
more flexibility, and shouldn't be difficult to
implement. There have been more than a few times where
I did the wrong thing with the current ra.sh script,
and have messed up a load.

Perhaps this prompt could read like this:

Apply difference transcript or edit? ( y | n | e )

Thanks - Willie

Original comment by: wnorthway

**Comment by linuxjackto1** [comment]
thanks www.movied.org
