### ISSUE TITLE
Identify client via MAC address

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#244]
Would it be possible to add the option of identifying the clients via 
ethernet MAC address?  I know that radmind is mostly made for unix 
admins, but with the Radmind Assistant non-unix geeks (like me) have 
been able to use Radmind to set deployment strategies.

In different forums or mailing list I've seen a lot  of people looking for the 
same functionnality as Assimilator had in Mac OS 9.  That is what I've 
been trying to get.  The only current choices are to use SSL keys or 
Rendez-Vous names, but the Rendez-vous names don't work across 
subnets.  As for generating and managing SSL keys, that is beyond my 
ability, even after trying to find examples and docs on the web.

It just seems that it would be sooooo simple if the client and server could 
identify the station via the ethernet MAC address.

How much work would be involved in adding this?

Thank you for your time, and for the great software.

Manuel

Original comment by: themactech

**Comment by linuxjackto1** [comment]
thanks www.movied.org
