### ISSUE TITLE
Add Special Entry bug

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#254]
Unless I misunderstand special files then this is a bug:

See attached img

Would it not make sense to allow free form entry when selecting the 
client. In this case I have a group of clients that use final cut, I want to put 
192.168.1.51 in the top menu, to send the licnese file to teh first Mac. 
The server manager won't let me.

Original comment by: ofirgal

**Comment by linuxjackto1** [comment]
thanks www.movied.org
