### ISSUE TITLE
libsnet cannot find ssl libraries

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#28]
radmind 1.6.0rc4 on Solaris 9.

$ ./configure --with-ssl=/opt/local
[snip]
checking for SSL_accept in -lssl... no
checking for ssl... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for SSLeay_version in -lcrypto... yes
checking for openssl/ssl.h... (cached) yes
[snip]
configure: configuring in libsnet
configure: running /bin/bash './configure'
--prefix=/usr/local  --with-sasl=no
--cache-file=/dev/null --srcdir=.
[snip]
checking for SSL_accept in -lssl... no
checking for ssl... configure: error: cannot find ssl
libraries
configure: error: /bin/bash './configure' failed for
libsnet

It looks like ./configure isn't passing my parameters
to the libsnet configure.

Original comment by: selsky

**Comment by linuxjackto1** [comment]
thanks www.movied.org
