### ISSUE TITLE
ktcheck is partialy case independent

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#31]
ktcheck is inconsistent on how it checks case of transcripts.  It ignores 
case when checking if a transcript needs to be replaced, but is strict 
about case when it decides to delete transcripts for the clean option.

To test this, change the case of a transcript and change the case of the 
transcript in the command file.

pick a transcript such as
a.T
update the transcripts on the client so that a.T is downloadeed
On the server:
change a.T to A.T
change to A.T in the command file.

on the client
/usr/local/bin/ktcheck -CZ 5 -c sha1 -h radmindserver

You will see that it does not download a new transcript A.T since it does 
the compare in a case independent way.  It will however delete the a.T file 
during the cleanup phase (the -C option)

Then fsdiff will fail since it cannot find A.T that is listed in the command 
file since it was deleted.   A second call to ktcheck will download the new 
file and everything will work.

Original comment by: shannahs

**Comment by linuxjackto1** [comment]
thanks www.movied.org
