### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by noobergeek** [Radmind/radmind#316]
Your project is missing all of the original tags.  You may want to incorporate them since they mark the existing releases.

**Comment by OmgImAlexis** [comment]
PING: @pdarragh 

There's also a lot of issues that can probably be closed since some are over 10 years old.

**Comment by pdarragh** [comment]
@noobergeek not sure how to migrate that now... I don't think I have access to the original repository any longer. I migrated Radmind to GitHub for historical preservation more than anything else; I have no plans to update anything ( @OmgImAlexis this includes resolving any existing issues). If either of you can offer any direct help (pull requests, etc.) I can approve those, but I haven't touched anything in Radmind for a few years.

**Comment by noobergeek** [comment]
I don't have permission to push changes to your repo, but it should be fairly trivial to incorporate the tags:

clone the original (it's still there):
git clone git://git.code.sf.net/p/radmind/radmind

change the URL in the cloned copy to your project URL:
cd radmind
git remote set-url origin https://github.com/Radmind/radmind.git

then push only the tags:
git push --tags

Then you should be good to go.  (You can discard the clone after you're done.)

**Comment by uurazzle** [comment]
Hello:

There wasn't interest from the community for supporting this project after we migrated it from source forge. So, no other work has been done outside the initial migration of the code source.

Thanks for the feedback.

> On May 19, 2017, at 12:22 PM, noobergeek <notifications@github.com> wrote:
> 
> I don't have permission to push changes to your repo, but it should be fairly trivial to incorporate the tags:
> 
> clone the original (it's still there):
> git clone git://git.code.sf.net/p/radmind/radmind
> 
> change the URL in the cloned copy to your project URL:
> cd radmind
> git remote set-url origin https://github.com/Radmind/radmind.git
> 
> then push only the tags:
> git push --tags
> 
> Then you should be good to go. (You can discard the clone after you're done.)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


Thanks:

Richard Glaser
University of Utah, Marriott Library ITS
richard.glaser@utah.edu

**Comment by hfath** [comment]
On Fri, 19 May 2017 11:46:34 -0700, Richard Glaser wrote:
> There wasn't interest from the community for supporting this project 
> after we migrated it from source forge. So, no other work has been 
> done outside the initial migration of the code source.

Well, it was kind of puzzling ath the time - you sent a call for 
volunteers, asked a handful of people who replied for their gitlab 
handles, and that was the end of it. I for my part am still interested 
in helping maintain Radmind.

About the bug database: The complete database is still on sourceforge, 
and having an incomplete copy at github is worse than none. IMHO, since 
you (as in: whoever was involved at the time) decided not to complete 
the bug database conversion, the github copy should have been deleted.

Cheerio,
hauke

-- 
     The ASCII Ribbon Campaign                    Hauke Fath
()     No HTML/RTF in email            Institut für Nachrichtentechnik
/\     No Word docs in email                     TU Darmstadt
     Respect for open standards              Ruf +49-6151-16-21344

**Comment by uurazzle** [comment]
ok, we will delete it.

Thanks:

Richard Glaser
University of Utah, Marriott Library ITS
richard.glaser@utah.edu

**Comment by magnusviri** [comment]
I pushed the tags from SF to github.  Closing.
