### ISSUE TITLE
Error Message Installing Tools

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#34]
The Radmind Assistant 1.0.0rc2, on launch prompts

Install Radmind Tools

Click OK to upgrade the radmind tools on this system.

Then displays error message...

Error

Couldn't open Radmind Tool Installer. You may need to reinstall the 
Radmind Assistant before continuing.

But, launches the radmind tools installer.

So, it shouldn't display the error unless it can't open the Radmind Tool 
installer, but it does it when it can open the installer.

Original comment by: uurazzle

**Comment by linuxjackto1** [comment]
thanks www.movied.org
