### ISSUE TITLE
Additional Audit Options

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#40]
Here is another feature request, to allow the Radmind Transcript Editor 
support addition audit options, like if the user is using relative paths, that 
when the perform an audio it will list transcript lines with absolute paths. 
Or other options like incorrect user or groups in transcript lines. For 
example, in some environments people might create/test overload with 
non-admin accounts and accidentally add files with those incorrect user/
groups. So, if you had a option to allow user to enter in allowed user/
groups, else display lines when performing audit.

Original comment by: uurazzle

**Comment by linuxjackto1** [comment]
thanks www.movied.org
