### ISSUE TITLE
Transcript Editor - Hidden Files Error

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#45]
Trying to add a hidden file, I get the following error with the Transcript 
Editor 0.7.7rc1.

Error Reading Transcript

ZeroLink: could not load .o file: /Volumes/dva/Users/admorten/src/
radmind-assistant/rte/build/RTE.build/Default/rteauthexec.build/
Objects-normal/ppc/copy.ob
ZeroLink: could not load .o file: /Volumes/dva/Users/admorten/src/
radmind-assistant/rte/build/RTE.build/Default/rteauthexec.build/
Objects-normal/ppc/selfrepair.ob
ZeroLink: could not load .o file: /Volumes/dva/Users/admorten/src/
radmind-assistant/rte/build/RTE.build/Default/rteauthexec.build/
Objects-normal/ppc/rteauthexec.ob

Original comment by: uurazzle

**Comment by linuxjackto1** [comment]
thanks www.movied.org
