### ISSUE TITLE
Transcript Editor - Editing Multiple Transcript Lines

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#49]
The Radmind Transcript Editor 0.7.7rc1 (0.7.7rc1) allows to select 
multiple transcript lines and the "Edit" tab allows you to enter in 
modfications for owner & group, say you want to change the UID or GID, 
but doesn't retain the changes if you select an individual transcript lines 
in the multiple selection and nothing was edited.

Maybe, if you don't want to allow editing multiple lines don't allow 
entering anything in owner & group text boxes. The other check boxes 
don't allow selection, but it isn't obvious that this is supported vs a bug. 
Maybe better direction would be deactivating the edit tab when selecting 
multiple items.

It would be a cool feature to allow making edits on multiple lines.

Original comment by: uurazzle

**Comment by linuxjackto1** [comment]
thanks www.movied.org
