### ISSUE TITLE
Transcript Editor - Convert

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#54]
Radmind Transcript Editor 0.7.7rc1 (0.7.7rc1) doesn't convert if there is is 
combination of paths that start with "." and "/". For example, if you 
comment out line that starts with ".", then convert to "/", then uncomment 
the commented line the path will start with ".", but if you decide that you 
want all your transcript lines to start with "/" it doesn't allow it. It will 
allow conversion to "/" for the one uncommented line. Also, the issue is 
the same but for "/".

Original comment by: uurazzle

**Comment by linuxjackto1** [comment]
thanks www.movied.org
