### ISSUE TITLE
Transcript Editor - Editing Transcript Lines

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#57]
Radmind Transcript Editor 0.7.7rc1 (0.7.7rc1), does appear to retain some 
edits to transcripts lines. For example, changes to "Owner", "Group" "Octal 
Representation of Mode" or editing anything using the entire transcript 
line. 

It appears using the permissions or special mode bits (SetUID, SetGID & 
Sticky) checkboxes are retained.

Original comment by: uurazzle

**Comment by linuxjackto1** [comment]
thanks www.movied.org
