### ISSUE TITLE
Radmind Assistant - About Shows Previous Version

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#59]
A minor issue, but if you launch Radmind Assistant and it prompts you 
to upgrade the radmind tools and then install the upgraded tools. The 
Radmind Assistant -&gt; About Radmind Assistant -&gt; Installed Radmind 
Tools

For example, it shows...

/usr/local/bin/fsdiff:
1.5.1
sha1
sha
md5
md2
dss1
mdc2
ripemd160

/usr/local/bin/ktcheck:
1.5.1
sha1
sha
md5
md2
dss1
mdc2
ripemd160

/usr/local/bin/lapply:
1.5.1
sha1
sha
md5
md2
dss1
mdc2
ripemd160

/usr/local/bin/lcksum:
1.5.1
sha1
sha
md5
md2
dss1
mdc2
ripemd160

/usr/local/bin/lcreate:
1.5.1
sha1
sha
md5
md2
dss1
mdc2
ripemd160

/usr/local/bin/lfdiff:
1.5.1

/usr/local/bin/lmerge:
1.5.1

/usr/local/bin/twhich:
1.5.1

/usr/local/sbin/radmind:
1.5.1

But, actually...

1.6.0rc6 version of the tools was installed.

If I quit and relaunch Radmind Assistant it shows the upgraded version.

Original comment by: uurazzle

**Comment by linuxjackto1** [comment]
thanks www.movied.org
