### ISSUE TITLE
Radmind Transcript Editor - Show Info

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#62]
A minor issue, but you can't select multiple transcript lines and click the 
"Show Info" button or "Show Info" command, but you can select a single 
line the click "Show Info" button or "Show Info" command and then select 
multiple lines.

It seems that if editing multiple lines is supported that you should be able 
to use "Show Info" button or "Show Info" command.

Original comment by: uurazzle

**Comment by linuxjackto1** [comment]
thanks www.movied.org
