### ISSUE TITLE
Mac OS X Installer - ReadMe Changelog

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#72]
FYI:

I would recommend, updating the ReadMe changelog section to use the 
updated web site for the changelog?  

Versus the old one:

http://radmind.org/changelog.html

Since it isn't updated with any versions after Radmind 1.5.

I think this change will ease confusing and tracking down information for 
those using radmind.

Also Is there a link that will list changelog of all previous versions (i.e. 
1.5.2 & 1.6) of Radmind and GUI tools like old site? 

For example, to get info on changelog you need to go to each separate.

https://sourceforge.net/project/shownotes.php?
group_id=141444&release_id=404107

It would be nice having a page that lists all version changelogs, for 
comparison, etc.

Original comment by: uurazzle

**Comment by linuxjackto1** [comment]
thanks www.movied.org
