### ISSUE TITLE
radmind assistant 1.0 crash

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#80]
1, run client set up without setting up the server first. eventually it 
crashed (iirc ,when it tried to upload to a non-existant server).

2, run the client process without moving the transcript to production on 
the radmind server. after uploading the negative transcript and 
proceeding to create the loadset it will crash with a 551 error saying file 
already exists.

i didnt expect radmind assistant to work under either of these 
circumstances but i didnt expect a crash.

Original comment by: marknassy

**Comment by linuxjackto1** [comment]
thanks www.movied.org
