### ISSUE TITLE
radmind assistant 1.0 crash

### ISSUE THREAD

**Issue by pdarragh** [Radmind/radmind#82]
i am using radmind assistant 1.0 to create and upload a negative 
transcript. i am getting an error message indicating the --l option is not 
supported. i have both the client and the server set to 0 (no security) after 
some initial changes back and forth. the assistant crashes after the error 
message is displayed. anyone know what i am doing wrong. this is a fresh 
os x install, reformat and install and update to 10.4.6. i dont know if it is 
related, but this occurred after i had a problem on the radmind server 
with the default negative desktop transcript giving me an incorrect sort 
order (when checksums were disabled) in server manager. i deleted the 
negative transcript on the server.

$ cat /Library/Logs/Console/501/console.log
...

2006-04-09 20:15:51.204 Radmind Assistant[543] error: usage: lcreate [ 
-%FlnNrTV ] [ -q | -v | -i ] [ -c checksum ] [ -h host ] [ -p port ] [ -t 
stored-name ] [ -U user ] [ -w auth-level ] [ -x ca-pem-file ] [ -y cert-
pem-file] [ -z key-pem-file ] [ -Z compression-level ] create-able-
transcript
Apr  9 20:15:51 mac-01-0000 crashdump[549]: Radmind Assistant 
crashed
Apr  9 20:15:51 mac-01-0000 crashdump[549]: crash report written to: /
Users/admin/Library/Logs/CrashReporter/Radmind Assistant.crash.log

i cant find where the radmind assistant files its logs so i have attached a 
screen capture of what i see before the crash. i checked in /var/
system.log.

i have also attached the crash log with this message.

Original comment by: marknassy

**Comment by linuxjackto1** [comment]
thanks www.movied.org
